import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import "@/assets/css/sidebar.css";
import "@/assets/css/dropdownmenu.css";
import "@/assets/css/progress.css";
import {Toaster} from "react-hot-toast";
import "react-loading-skeleton/dist/skeleton.css";
export const metadata = {
  title:"Inventory",
  description:"Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en bn">
      <body>
        {children}
        <Toaster position="top-center"/>
      </body>
    </html>
  );
}
